### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by PuneetKohli** [vikram-mm/Traffic-Sign-Detection-YOLO#1]
Hey Vikram,

Your code seems really promising. I am trying to run YOLO on the Traffic Sign Dataset myself.

Could you please either (a) let me know the steps to run your code, or (b) let me know the general steps to get the BTSD working with YOLO?

**Comment by PuneetKohli** [comment]
I think my biggest concern now is that yolo requires 448x448 input data but the BTS dataset images are in the range of around 128x128 on average. How are you dealing with this?

**Comment by vikram-mm** [comment]
Hey Puneet!

Sorry for the delay, if you are still looking for it - this should solve your doubt - [https://github.com/vikram-mm/Traffic-Sign-Detection-YOLO/blob/b7ebab5eac39f256c09e58cd1e7ac42dd9a1477a/btsd.py#L46](url)
